<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function page_block_theme($existing, $type, $theme, $path) {
  $variables = [
    'page_block' => [
      'variables' => [
        'title' => '',
        'page' => NULL,
        'settings' => NULL,
      ],
      'template' => 'page--block',
    ],
  ];

  return $variables;
}
