views.field.product_importer:
  type: views_field
  label: 'Product Importer'
  mapping:
    importer:
      type: string
      label: 'Which importer label to use: entity or plugin'

views.filter_value.price_filter:
  type: sequence
  label: 'Price'
  sequence:
    type: string
    label: 'Price'