<?php

/**
 * @file
 * Contains drush9_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drush9_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drush9_example module.
    case 'help.page.drush9_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides examples for writing custom Drush 9 commands.') . '</p>';
      return $output;

    default:
  }
}
