<?php
/**
 * @file
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.products':
      $output  = '';
      $output .= '<h3>'.t('About').'</h3>';
      $output .= '<p>'.t('This is an example module'). '</p>';
      return $output;
    default:
  }

}




