# Product entity menu items
entity.product.collection:
  title: 'Product List'
  route_name: entity.product.collection
  description: 'List Product entities'
  parent: system.admin_structure
  weight: 100

# Importer entity menu items
entity.importer.collection:
  title: 'Importer'
  route_name: entity.importer.collection
  description: 'List Importer entities'
  parent: system.admin_structure
  weight: 99
# Price menu items definition
entity.price.collection:
  title: 'Price list'
  route_name: entity.price.collection
  description: 'List Price entities'
  parent: system.admin_structure
  weight: 100

price.admin.structure.settings:
  title: 'Price settings'
  description: 'Configure Price entities'
  route_name: price.settings
  parent: system.admin_structure
