<?php

/**
 * @file
 * Contains lazy_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lazy_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lazy_service module.
    case 'help.page.lazy_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lazy_service_theme() {
  return [
    'lazy_service' => [
      'variables' => ['markup'=>NULL]
    ],
  ];
}
