<?php

/**
 * @file
 * Contains my_subscriber.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_subscriber_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_subscriber module.
    case 'help.page.my_subscriber':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}



/**
 * Implements hook_theme().
 */
function my_subscriber_theme() {
  return [
    'my_subscriber' => [
      'render element' => 'children',
    ],
  ];
}
